name: Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar manualmente el workflow

jobs:
  terraform:
    name: Plan Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  manual_approval:
    name: Aprobación Manual
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Esperar aprobación manual
        uses: peter-evans/repository-dispatch@v1
        with:
          event_type: wait-for-approval

  apply_terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest
    needs: manual_approval

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Apply
        run: terraform apply -auto-approve
