name: Terraform CI/CD

# Ejecuta el flujo de trabajo en un push o pull request al branch principal
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
    # Config el repo y checkea el código
    - name: Checkout repository
      uses: actions/checkout@v2

    # Se arranca el terraform
    - name: Terraform Init
      run: terraform init

    # Se realiza el plan
    - name: Terraform Plan
      run: terraform plan

    # Espera de aprobacion manual
    - name: Wait for Approval Event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT_TOKEN }} 
        repository: JorgeFR85/sdg-jorge
        event-type: wait-for-approval
