name: 'Terraform Kubernetes Deploy'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    # Paso 1: Inicializar Terraform
    - name: Initialize Terraform
      run: terraform init

    # Paso 2: Generar el plan de Terraform y guardarlo en un archivo llamado 'tfplan'
    - name: Generate Terraform Plan
      run: terraform plan -out=tfplan

    # Paso 3: Aplicar el plan generado
    - name: Apply Terraform Plan
      run: terraform apply -auto-approve tfplan
