name: Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite iniciar manualmente el workflow si es necesario

jobs:
  terraform:
    name: Plan y Aplicar Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
