name: Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar manualmente el workflow si es necesario

jobs:
  terraform:
    name: Plan Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

  manual_approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: terraform # Este paso depende del trabajo de terraform

    steps:
      - name: Esperar Aprobación Manual
        uses: hmarr/auto-approve-action@v2 # Espera la aprobación manual

  apply_terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest
    needs: manual_approval # Depende de la aprobación manual

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
